apiVersion: v1
kind: Service
metadata:
  name: dbservice
  namespace: services
spec:
  ports:
    - nodePort: 31281
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: dbservice
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbservice
  namespace: services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbservice
  template:
    metadata:
      labels:
        app: dbservice
    spec:
      containers:
        - image: mysql:latest
          name: dbservice
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: rootroot
            - name: MYSQL_HOST
              value: dbservice
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_USERNAME
              value: root
            - name: MYSQL_PASSWORD
              value: rootroot
            - name: MYSQL_DATABASE
              value: cloudConfiguratorDB
      restartPolicy: Always
