apiVersion: v1
kind: Service
metadata:
  name: dbservice
  namespace: services
spec:
  ports:
    - nodePort: 31281
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: dbservice
  type: NodePort
---
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  namespace: services
type: Opaque
data:
  password: cm9vdHJvb3Q=
  username: cm9vdA==
  database: Y2xvdWRDb25maWd1cmF0b3JEQg==
  root-password: cm9vdHJvb3Q=
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbservice
  namespace: services
spec:
  selector:
    matchLabels:
      app: dbservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: dbservice
    spec:
      containers:
      - image: mysql:8.0
        name: dbservice
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: root-password
        - name: MYSQL_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: database
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: mysql-pv-claim

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv-volume
  namespace: services
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: services
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi

      