apiVersion: v1
kind: Namespace
metadata:
  name: db
---

apiVersion: v1
kind: Service
metadata:
  name: dbservice
  namespace: db
spec:
  ports:
    - nodePort: 31281
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: dbservice
  type: NodePort

