apiVersion: v1
kind: Namespace
metadata:
  name: db
---

apiVersion: v1
kind: Service
metadata:
  name: dbservice
  namespace: db
spec:
  ports:
    - nodePort: 31281
      port: 3306
      protocol: TCP
      targetPort: 3306
  selector:
    app: dbservice
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dbservice
  namespace: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbservice
  template:
    metadata:
      labels:
        app: dbservice
    spec:
      containers:
        - image: monicapauline/db-service-image
          imagePullPolicy: IfNotPresent
          name: dbservice
          env:
            - name: DATASERVICE_HOST
              value: "dataservice.services"
      restartPolicy: Always
